name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      # ------------Premier LS------------
      - run: ls
      
      # ------------Checkout au repo------------
      - uses: actions/checkout@v4
        with:
          repository: 'Paum2tair/coursDeDevOps'
          
      # ------------Deuxième LS------------
      - run: ls

      # ------------Gestion de la version------------
      - name: Gestion de la version
        run: |
           VERSION=$(cat version.txt)
            echo "Notre version actuelle est : $VERSION"

            # Incrémenter la version
            NEW_VERSION=$(echo "$VERSION + 0.1" | bc)
            
            # Mettre à jour la version dans version.txt
            echo "$NEW_VERSION" > version.txt
        
            # Mettre la nouvelle version dans l'environnement GitHub
            echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
        
            # Afficher la nouvelle version
            echo "Notre nouvelle version est : $NEW_VERSION"

      # ------------Connexion à DockerHub------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ------------Mise en place de QEMU------------    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      # ------------Mise en place de Docker Buildx------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ------------Build du conteneur puis push de ce dernier------------
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: paum2tair/antoine-provain:${{ vars.IMAGE_ANTOINE_VERSION_TYPE }}$(cat version.txt) 

#checkout
#ls
#build
#images
#push
#pas de creds en clair
