name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      # ------------Premier LS------------
      - run: ls
      
      # ------------Checkout au repo------------
      - uses: actions/checkout@v4
        with:
          repository: 'Paum2tair/coursDeDevOps'
          
      # ------------Deuxième LS------------
      - run: ls

      # ------------Deuxième LS------------
      - name: Gestion de la version
        run: |
          ${{ vars.IMAGE_ANTOINE_VERSION_NUM }}= ${{ vars.IMAGE_ANTOINE_VERSION_NUM }} + 0.1
          echo "Notre version est : ${{ vars.IMAGE_ANTOINE_VERSION_NUM }}"

      # ------------Connexion à DockerHub------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ------------Mise en place de QEMU------------    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      # ------------Mise en place de Docker Buildx------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ------------Build du conteneur puis push de ce dernier------------
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: paum2tair/antoine-provain:${{ vars.IMAGE_ANTOINE_VERSION_TYPE }}${{ vars.IMAGE_ANTOINE_VERSION_NUM }}

#checkout
#ls
#build
#images
#push
#pas de creds en clair
